### ISSUE TITLE
Method not found [404]

### ISSUE THREAD

**Issue by barbaroskurt** [msavin/Mongol#104]
after installed mongol below error appeared in web-socket, when remove package it disappear;
it doesn't give any error on browser console or meteor console, i guess something suppress it.

```
a["{\"msg\":\"result\",\"id\":\"2\",\"error\":{\"error\":404,\"reason\":\"Method not found\",\"message\":\"Method not found [404]\",\"errorType\":\"Meteor.Error\"}}"]
```

and kadira trace error report;

```
message: Method not found [404] stack:
Error: Method not found [404]
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:628:1)
    at packages/meteorhacks:kadira/lib/hijack/wrap_session.js:52:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object].sessionProto.protocol_handlers.method (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:51:1)
    at packages/ddp/livedata_server.js:546:1
```

meteor version
```
1.1.0.3
```

meteor list
```
accounts-password               1.1.1  Password support for accounts
alanning:roles                  1.2.13  Role-based authorization
dbarrett:dropzonejs             4.0.2  Dropzone.js - an open source library that provides drag'n'drop file uploads with image previews
fortawesome:fontawesome         4.4.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
iron:router                     1.0.9  Routing specifically designed for Meteor
jquery                          1.11.3_2  Manipulate the DOM using CSS selectors
less                            1.0.14  The dynamic stylesheet language
meteor-platform                 1.2.2  Include a standard set of Meteor packages in your app
msavin:mongol                   1.1.5  The insanely handy development package for Meteor.
natestrauser:connection-banner  0.4.3  A banner that displays when meteor server is disconnected with countdown and reconnect option
okgrow:iron-router-autoscroll   0.0.9  Fixes page position after changing pages using Iron Router
peppelg:bootstrap-3-modal       1.0.3  Simple usage of bootstrap 3 modals.
reactive-var                    1.0.5  Reactive variable
twbs:bootstrap                  3.3.5  The most popular front-end framework for developing responsive, mobile first projects on the web.
zimme:active-route              2.3.1  Active route helpers
```

**Comment by tcastelli** [comment]
+1, but i can only see  Method not found [404] through Kadira Errors

**Comment by msavin** [comment]
HI there - we are a few versions up now - can you please let me know if this is still an issue?

**Comment by msavin** [comment]
Assuming this works now, so will close the issue
