### ISSUE TITLE
Error: use "new" to construct a Mongo.Collection

### ISSUE THREAD

**Issue by mbrookes** [msavin/Mongol#109]
Full stack trace:

```
W20150920-11:06:59.743(1)? (STDERR) /Users/mbrookes/.meteor/packages/meteor-tool/.1.1.4.16tvc2u++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150920-11:06:59.743(1)? (STDERR)                         throw(ex);
W20150920-11:06:59.743(1)? (STDERR)                               ^
W20150920-11:06:59.778(1)? (STDERR) Error: use "new" to construct a Mongo.Collection
W20150920-11:06:59.778(1)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:29:1)
W20150920-11:06:59.778(1)? (STDERR)     at new Ground.Collection (packages/ground:db/groundDB.server.js:80:1)
W20150920-11:06:59.778(1)? (STDERR)     at collections/entries.jsx:2:11
W20150920-11:06:59.779(1)? (STDERR)     at /Users/mbrookes/Projects/simple-todos-react/.meteor/local/build/programs/server/app/collections/entries.jsx.js:17:3
W20150920-11:06:59.779(1)? (STDERR)     at /Users/mbrookes/Projects/simple-todos-react/.meteor/local/build/programs/server/boot.js:222:10
W20150920-11:06:59.779(1)? (STDERR)     at Array.forEach (native)
W20150920-11:06:59.779(1)? (STDERR)     at Function._.each._.forEach (/Users/mbrookes/.meteor/packages/meteor-tool/.1.1.4.16tvc2u++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150920-11:06:59.779(1)? (STDERR)     at /Users/mbrookes/Projects/simple-todos-react/.meteor/local/build/programs/server/boot.js:117:5
```

`.meteor/packages`

```
meteor-platform
react
accounts-ui
accounts-password
kadira:flow-router
kadira:react-layout
ground:db
#izzilab:material-ui
sherdeadlock:fixed-data-table
ixdi:material-design-iconic-font
fortawesome:fontawesome
momentjs:moment
meteorhacks:npm
cosmos:browserify
npm-container
msavin:mongol
```

The offending line: 

```
Entries = new Ground.Collection("entries");
```

...so I'm guessing Mongol doesn't play nice with GroundDB?

**Comment by JackAdams** [comment]
I notice your `msavin:mongol` is after `ground:db`.  Take a look at #48 for the fix (in short, just put `msavin:mongol` before `ground:db` in the packages list).

**Comment by mbrookes** [comment]
Spot on @JackAdams - thanks for pointing this out (and for figuring this out in the first place in #48), and sorry for not checking closed issues first. Awesome piece of work with @msavin on this. What a timesaver!
