### ISSUE TITLE
What is the package meteortoys:toykit used for?

### ISSUE THREAD

**Issue by ghost** [msavin/Mongol#113]
You are using [meteortoys:toykit](https://atmospherejs.com/meteortoys/toykit) but in the install page it says "Do not install this package". 

This was giving me an error so i removed mongol package and i stopped getting the error

**Comment by cryptoquick** [comment]
I was getting this error, too. It looked kinda like this, right?

```
W20150929-17:26:19.561(-6)? (STDERR) /Users/xxx/.meteor/packages/meteor-tool/.1.1.9.nv791y++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150929-17:26:19.561(-6)? (STDERR)                        throw(ex);
W20150929-17:26:19.561(-6)? (STDERR)                              ^
W20150929-17:26:19.565(-6)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150929-17:26:19.566(-6)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150929-17:26:19.566(-6)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20150929-17:26:19.566(-6)? (STDERR)     at /Users/xxx/GitHub/xxx/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20150929-17:26:19.566(-6)? (STDERR)     at /Users/xxx/GitHub/xxx/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20150929-17:26:19.566(-6)? (STDERR)     at /Users/xxx/GitHub/xxx/.meteor/local/build/programs/server/boot.js:242:10
W20150929-17:26:19.566(-6)? (STDERR)     at Array.forEach (native)
W20150929-17:26:19.566(-6)? (STDERR)     at Function._.each._.forEach (/Users/xxx/.meteor/packages/meteor-tool/.1.1.9.nv791y++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150929-17:26:19.566(-6)? (STDERR)     at /Users/xxx/GitHub/xxx/.meteor/local/build/programs/server/boot.js:137:5
```

Regardless, I removed Mongol and it builds now.

**Comment by mshamblott** [comment]
The latest Meteor 1.2 update had a warning about meteortoys backwards compatibility.  I got  the same errors, deleted mongol and it built.  Meteor isn't as fun without Mongol though!

**Comment by tcastelli** [comment]
+1

**Comment by msavin** [comment]
Fixed - to reset add and remove the package :)

**Comment by NigelEarle** [comment]
@msavin gettting error `Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'ToyKit' of undefined` after installing `msavin:mognol`. Any suggestions or similar packages to install using `meteortoys:toykit`?
