### ISSUE TITLE
MeteorToys TypeError preventing startup: Property 'undefined' of object not a function

### ISSUE THREAD

**Issue by mikepaszkiewicz** [msavin/Mongol#116]
I'm @ Meteor 1.2.0.2, MeteorToys 1.0.0, and Mongol 1.2.0. Doesn't seem to be an issue with package load order, but preventing my app from starting. Any ideas?

```
W20150930-11:37:52.137(-4)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150930-11:37:52.137(-4)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150930-11:37:52.137(-4)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20150930-11:37:52.137(-4)? (STDERR)     at /Users/michaelpaszkiewicz/Meteor/habitat/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20150930-11:37:52.137(-4)? (STDERR)     at /Users/michaelpaszkiewicz/Meteor/habitat/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20150930-11:37:52.137(-4)? (STDERR)     at /Users/michaelpaszkiewicz/Meteor/habitat/.meteor/local/build/programs/server/boot.js:242:10
W20150930-11:37:52.137(-4)? (STDERR)     at Array.forEach (native)
W20150930-11:37:52.138(-4)? (STDERR)     at Function._.each._.forEach (/Users/michaelpaszkiewicz/.meteor/packages/meteor-tool/.1.1.9.13so0y5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-11:37:52.138(-4)? (STDERR)     at /Users/michaelpaszkiewicz/Meteor/habitat/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

**Comment by jesperordrup** [comment]
I've got the same errormessage.

Solution worked until upgrading to meteor 1.2

Removing  msavin:mongol from solution makes it work.

**Comment by elie222** [comment]
+1

**Comment by msavin** [comment]
I just pushed up an update.. I have no idea what broke but it looks like its working now. Can you guys please confirm?

I am testing on todos app with Meteor 1.2

**Comment by elie222** [comment]
Working now

**Comment by jesperordrup** [comment]
YES! Thank you!
