### ISSUE TITLE
Server error on v1.2

### ISSUE THREAD

**Issue by brunolemos** [msavin/Mongol#117]
```
20151001-22:48:34.268(-3)? (STDERR) /Users/brunolemos/.meteor/packages/meteor-tool/.1.1.9.ej32mt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151001-22:48:34.268(-3)? (STDERR)                        throw(ex);
W20151001-22:48:34.268(-3)? (STDERR)                              ^
W20151001-22:48:34.276(-3)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20151001-22:48:34.276(-3)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20151001-22:48:34.276(-3)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20151001-22:48:34.276(-3)? (STDERR)     at /Users/brunolemos/Documents/Projects/meteor/flatnotes-web/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20151001-22:48:34.277(-3)? (STDERR)     at /Users/brunolemos/Documents/Projects/meteor/flatnotes-web/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20151001-22:48:34.277(-3)? (STDERR)     at /Users/brunolemos/Documents/Projects/meteor/flatnotes-web/.meteor/local/build/programs/server/boot.js:242:10
W20151001-22:48:34.277(-3)? (STDERR)     at Array.forEach (native)
W20151001-22:48:34.277(-3)? (STDERR)     at Function._.each._.forEach (/Users/brunolemos/.meteor/packages/meteor-tool/.1.1.9.ej32mt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151001-22:48:34.277(-3)? (STDERR)     at /Users/brunolemos/Documents/Projects/meteor/flatnotes-web/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20151001-22:48:39.834(-3)? (STDERR)          
W20151001-22:48:39.835(-3)? (STDERR) /Users/brunolemos/.meteor/packages/meteor-tool/.1.1.9.ej32mt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151001-22:48:39.835(-3)? (STDERR)                        throw(ex);
W20151001-22:48:39.835(-3)? (STDERR)                              ^
W20151001-22:48:39.843(-3)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20151001-22:48:39.843(-3)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20151001-22:48:39.843(-3)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20151001-22:48:39.843(-3)? (STDERR)     at /Users/brunolemos/Documents/Projects/meteor/flatnotes-web/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20151001-22:48:39.843(-3)? (STDERR)     at /Users/brunolemos/Documents/Projects/meteor/flatnotes-web/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20151001-22:48:39.843(-3)? (STDERR)     at /Users/brunolemos/Documents/Projects/meteor/flatnotes-web/.meteor/local/build/programs/server/boot.js:242:10
W20151001-22:48:39.844(-3)? (STDERR)     at Array.forEach (native)
W20151001-22:48:39.844(-3)? (STDERR)     at Function._.each._.forEach (/Users/brunolemos/.meteor/packages/meteor-tool/.1.1.9.ej32mt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151001-22:48:39.844(-3)? (STDERR)     at /Users/brunolemos/Documents/Projects/meteor/flatnotes-web/.meteor/local/build/programs/server/boot.js:137:5
```

**Comment by mshamblott** [comment]
I got the same error.  Removing Mongol / jetSetter or possibly anything dependent on meteortoys allows build.

**Comment by simongroll** [comment]
+1 (building on Windows)

**Comment by msavin** [comment]
Sorry for the inconvenience, I'm looking into it. It's strange because it works then breaks.

**Comment by simongroll** [comment]
:+1: 
Thanks!

**Comment by msolters** [comment]
I have two observations.
-  On my system at least -- Ubuntu 15.04 -- if I add `msavin:mongol` _while_ the Meteor 1.2 server is running, it works fine.  It's only when I start a Meteor 1.2 server that has it already included that I get this error. 
-  I also pushed a project with mongol added and working to a repo, and when I cloned it to another system (also Ubuntu 15.04) and started the Meteor server, it built and threw no errors -- but CTRL+M had no effect whatsoever.  Removing and adding mongol brought it back to a working condition.  Very strange.

**Comment by tommiley** [comment]
I also am getting this

**Comment by mikepaszkiewicz** [comment]
Had it working fine as of the issue I posted yesterday. My meteor.com server crashed overnight with same logs, now can't even run locally without removing allthings/mongol. Very strange.

**Comment by mayankchhabra** [comment]
I'm getting the same error too (Meteor 1.2.0.2, OS X)

**Comment by msavin** [comment]
Ok - I _hope_ its fixed. Please add/remove to try again :8ball:

**Comment by mayankchhabra** [comment]
Yes, it works! Thanks a lot! :+1:

**Comment by gdw2** [comment]
Did you just republish?  I don't see any code changes in github.

**Comment by tommiley** [comment]
Working for me as well. Thanks Max.

**Comment by stefanve** [comment]
After removing/re-adding the above problem went away but I still have the issue reported here: https://github.com/msavin/Mongol/issues/118

**Comment by msavin** [comment]
Nice - glad its working now. Also, folks, check out http://toys.meteor.com :)

@gdw2 Mongol went closed source - but will continue to be improved and free
