### ISSUE TITLE
MeteorToys error on server

### ISSUE THREAD

**Issue by jorisroling** [msavin/Mongol#119]
Server logs get cluttered with exceptions (below).
msavin:jetsetter @ 1.3.0
msavin:mongol @1.4.1

``` js
Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'ToyKit' of undefined
    at [object Object].Meteor.(anonymous function).MeteorToys (packages/msavin_mongol/server/methods.js:2:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (livedata_server.js:1692:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/Users/joris/.meteor/packages/promise/.0.5.0.4k4m85++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/joris/.meteor/packages/promise/.0.5.0.4k4m85++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
```

**Comment by msavin** [comment]
Can't get to this right now unfortunately. Check out http://toys.meteor.com in the meanwhile though :)

**Comment by msavin** [comment]
Okay it looks its fixed; would be great if you can confirm. In the meanwhile, closing this thread

**Comment by jorisroling** [comment]
I still get the error...

**Comment by samoilis** [comment]
me too
msavin:jetsetter@1.3.1
msavin:mongol@1.4.3

TypeError: Cannot read property 'ToyKit' of undefined 
    at [object Object].Meteor.(anonymous function).MeteorToys (packages/msavin_mongol/server/methods.js:1:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (livedata_server.js:1692:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (C:\Users\Administrator\AppData\Local.meteor\packages\promise\0.5.0\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:45:5)
    at doResolve (C:\Users\Administrator\AppData\Local.meteor\packages\promise\0.5.0\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:171:13)

**Comment by msavin** [comment]
Does it still work or nope? Try the Meteor Toys package this weekend. I think some of trial stuff I built in is causing this. I'll deploy the other version tomorrow. Sorry for the inconvenience.

**Comment by jorisroling** [comment]
Works, thanks!

**Comment by jorisroling** [comment]
Too fast, still get this on server:

20151011-23:35:17.023(2)? Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'ToyKit' of undefined
I20151011-23:35:17.023(2)?     at [object Object].Meteor.(anonymous function).MeteorToys (packages/msavin_mongol/server/methods.js:1:1)
I20151011-23:35:17.023(2)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
I20151011-23:35:17.024(2)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20151011-23:35:17.024(2)?     at livedata_server.js:708:19
I20151011-23:35:17.024(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151011-23:35:17.024(2)?     at livedata_server.js:706:40
I20151011-23:35:17.024(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151011-23:35:17.025(2)?     at livedata_server.js:704:46
I20151011-23:35:17.025(2)?     at tryCallTwo (/Users/joris/.meteor/packages/promise/.0.5.0.4k4m85++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151011-23:35:17.025(2)?     at doResolve (/Users/joris/.meteor/packages/promise/.0.5.0.4k4m85++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)

**Comment by casual-will** [comment]
This is still an issue.

**Comment by nickredmark** [comment]
+1

**Comment by serut** [comment]
+1

**Comment by Xsandor** [comment]
+1

**Comment by mhagmajer** [comment]
@msavin, this still happens on mongol 1.4.3

**Comment by jesperordrup** [comment]
Got the same problem. This issue is closed?

**Comment by MartinBucko** [comment]
+1
- 1.4.3
- Meteor 1.2.0.2

**Comment by MilosStanic** [comment]
+1

**Comment by maximebodereau** [comment]
+1

**Comment by adamclark64** [comment]
wouldnt you know. I have this issue as well

**Comment by hafizali05** [comment]
no support?

**Comment by thomasspiesser** [comment]
same same
msavin:mongol 1.4.3
Meteor 1.2.0.2

**Comment by akaushik** [comment]
when we can see this rectified? 
msavin:mongol 1.4.3
Meteor 1.2.0.2

**Comment by selaias** [comment]
removing msavin:mongol and any other related packages and  just adding meteortoys:allthings
fixes the issue but then you get a big bunch of packages 

gwendall:body-events     added, version 0.1.6 
meteortoys:allthings     added, version 2.1.1
meteortoys:authenticate  added, version 2.0.0
meteortoys:autopub       added, version 2.0.1
meteortoys:blueprint     added, version 2.0.2
meteortoys:email         added, version 2.0.1
meteortoys:hotreload     added, version 2.0.1
meteortoys:listen        added, version 2.0.0
meteortoys:method        added, version 2.0.0
meteortoys:pro           added, version 2.0.0
meteortoys:pub           added, version 2.0.0
meteortoys:result        added, version 2.0.1
meteortoys:shell         added, version 2.0.1
meteortoys:status        added, version 2.0.0
meteortoys:sub           added, version 2.0.0
meteortoys:throttle      added, version 2.0.0
meteortoys:toypro        added, version 2.0.0
msavin:jetsetter         added, version 1.2.0

I guess i'll wait for a fix.
