### ISSUE TITLE
ToyKit of undefined after starting app

### ISSUE THREAD

**Issue by tcastelli** [msavin/Mongol#120]
``` javascript
Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'ToyKit' of undefined
I20151010-17:28:04.929(2)?     at [object Object].Meteor.(anonymous function).MeteorToys (packages/msavin_mongol/server/methods.js:1:1)
I20151010-17:28:04.930(2)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
I20151010-17:28:04.931(2)?     at packages/check/match.js:109:1
I20151010-17:28:04.931(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151010-17:28:04.932(2)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20151010-17:28:04.932(2)?     at maybeAuditArgumentChecks (livedata_server.js:1689:18)
I20151010-17:28:04.933(2)?     at livedata_server.js:708:19
I20151010-17:28:04.933(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151010-17:28:04.934(2)?     at livedata_server.js:706:40
I20151010-17:28:04.934(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

**Comment by ramify** [comment]
Getting the same error after updating today.

**Comment by liambluebox** [comment]
I get the same thing.

**Comment by oliroy** [comment]
+1

**Comment by jackkav** [comment]
+1

**Comment by msavin** [comment]
Should be corrected in the new version. Please let me know if it works by removing and re-adding your packages.
