### ISSUE TITLE
Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'ToyKit' of undefined

### ISSUE THREAD

**Issue by fishdude** [msavin/Mongol#121]
After updating a project to Meteor 1.2, i've started to receive the following error after server starts.

```
App running at: http://localhost:3000/
I20151012-01:20:17.474(-7)? Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'ToyKit' of undefined
I20151012-01:20:17.474(-7)?     at [object Object].Meteor.(anonymous function).MeteorToys (packages/msavin_mongol/server/methods.js:1:1)
I20151012-01:20:17.474(-7)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
I20151012-01:20:17.474(-7)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20151012-01:20:17.474(-7)?     at livedata_server.js:708:19
I20151012-01:20:17.475(-7)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20151012-01:20:17.475(-7)?     at livedata_server.js:706:40
I20151012-01:20:17.475(-7)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20151012-01:20:17.475(-7)?     at livedata_server.js:704:46
I20151012-01:20:17.475(-7)?     at tryCallTwo (/Users/fish/.meteor/packages/promise/.0.5.0.1fw1xve++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151012-01:20:17.475(-7)?     at doResolve (/Users/fish/.meteor/packages/promise/.0.5.0.1fw1xve++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151012-01:20:17.475(-7)?     at new Promise (/Users/fish/.meteor/packages/promise/.0.5.0.1fw1xve++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20151012-01:20:17.475(-7)?     at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
I20151012-01:20:17.476(-7)?     at livedata_server.js:548:43
```

```
Meteor 1.2.0.2
dburles:mongo-collection-instances  version 0.3.4
lai:collection-extensions           version 0.1.4
meteortoys:toykit                   version 2.1.1
msavin:mongol                       version 1.4.3
```

When I remove mongol the error is no longer thrown, but I would love to start using this incredibly useful tool again! Thanks for all of the terrific work.

**Comment by vseehausen** [comment]
+1 
Exception while invoking method 'MeteorToys' TypeError: Cannot read property 'ToyKit' of undefined

**Comment by warmbowski** [comment]
On the first day of the hackathon, I got that error when I installed mongol on a new project using 1.2.0.2 and tried hitting ctrl-m. Basically mongol wouldn't come up in the interface. So I removed the mongol package and added the full Meteor Toys that was offered for free. It came up in the interface and worked fine when I hi ctrl-m, but still complained with a similar error: 

```
20151012-23:53:24.856(-7)? Exception while invoking method 'MeteorToys_method_handlers' ReferenceError: Match is not defined
I20151012-23:53:24.858(-7)?     at [object Object].Meteor.(anonymous function).MeteorToys_method_handlers (packages/meteortoys_hotreload/config/config.js:1:1)
I20151012-23:53:24.858(-7)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20151012-23:53:24.858(-7)?     at livedata_server.js:708:19
I20151012-23:53:24.859(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151012-23:53:24.859(-7)?     at livedata_server.js:706:40
I20151012-23:53:24.859(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151012-23:53:24.860(-7)?     at livedata_server.js:704:46
I20151012-23:53:24.860(-7)?     at tryCallTwo (/Users/paul/.meteor/packages/promise/.0.5.0.kuytg4++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151012-23:53:24.861(-7)?     at doResolve (/Users/paul/.meteor/packages/promise/.0.5.0.kuytg4++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151012-23:53:24.861(-7)?     at new Promise (/Users/paul/.meteor/packages/promise/.0.5.0.kuytg4++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
```

**Comment by serut** [comment]
I can use this pluggin with the lastest Meteor version, this is my workflow : 
First, I removed the msavin:mongol package

```
[me@xxx src]$ meteor remove msavin:mongol

Changes to your project's package version selections:

dburles:mongo-collection-instances  removed from your project
lai:collection-extensions           removed from your project
msavin:mongol                       removed from your project

msavin:mongol: removed dependency 
```

Then I downloaded the entire msavin/Mongol as zip (you can clone the repo) and I put it in the packages directory.
I just had to edit the file package.js :  

```
Package.describe({
    name:    'msavin:mongol',
to  
Package.describe({
    name:    'mongol-master',
```

Then I add this package to my project. At this step, if you just add the package, you will see an error :

```
[me@xxx src]$ meteor add mongol-master
 => Errors while adding packages:             

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: msavin:jetsetter 1.0.20, was 1.3.1.
Constraints on package "msavin:jetsetter":

To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.
```

I think that this error needs more investigation. If I had --allow-incompatible-update, everything start to work. 

```
[me@xxx src]$ meteor add mongol-master --allow-incompatible-update

Changes to your project's package version selections:

aldeed:template-extension           added, version 3.4.3
babrahams:editable-json             added, version 0.4.3
dburles:mongo-collection-instances  added, version 0.3.4
gwendall:session-json               added, version 0.1.7
lai:collection-extensions           added, version 0.1.4
meteortoys:toykit*                  downgraded from 2.1.1 to 0.8.7
mongol-master                       added, version 1.0.101
msavin:jetsetter                    downgraded from 1.3.1 to 1.0.20


* These packages have been updated to new versions that are not backwards
compatible.

mongol-master: The insanely handy development package for Meteor.
```

Good luck.

**Comment by oliroy** [comment]
+1 on exception.

**Comment by JcBernack** [comment]
I get the exception on each page reload, but the UI is showing and working.

**Comment by adityamenon-iom** [comment]
I can confirm that the behavior is same for me as @JcBernack

**Comment by sylido** [comment]
+1

**Comment by sschuchlenz** [comment]
+1

**Comment by jurajkrivda** [comment]
+1

**Comment by msavin** [comment]
Hey folks, sorry for the delay. It should be resolved now. Please let me know how its working.

**Comment by jurajkrivda** [comment]
It works. Thank you.

**Comment by msavin** [comment]
Awesome - closing then :)

**Comment by fishdude** [comment]
Thanks @msavin!

**Comment by vseehausen** [comment]
Thanks. :-) Good Job.

**Comment by EranSch** [comment]
YOU THE MAN, SAVIN!! :+1: :+1:
