### ISSUE TITLE
Error with meteor 1.6.1-beta

### ISSUE THREAD

**Issue by RemyLespagnol** [msavin/Mongol#152]
Hi @msavin :)

When I have you package (msavin:mongol) in my project, I can't run it.
I have this problem : 

```
W20171214-14:17:03.743(1)? (STDERR) C:\Users\plesp\AppData\Local\.meteor\packages\meteor-tool\1.6.1-beta.18\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20171214-14:17:03.744(1)? (STDERR)                                             throw(ex);
W20171214-14:17:03.744(1)? (STDERR)                                             ^
W20171214-14:17:03.745(1)? (STDERR)
W20171214-14:17:03.745(1)? (STDERR) TypeError: Class constructor Collection cannot be invoked without 'new'
W20171214-14:17:03.746(1)? (STDERR)     at new _0x51eex8.(anonymous function) (packages\meteortoys_toykit.js:29:7185)
W20171214-14:17:03.746(1)? (STDERR)     at packages\meteortoys_toykit.js:29:8823
W20171214-14:17:03.746(1)? (STDERR)     at packages\meteortoys_toykit.js:32:4
W20171214-14:17:03.747(1)? (STDERR)     at packages\meteortoys_toykit.js:40:3
W20171214-14:17:03.747(1)? (STDERR)     at infos.forEach.info (C:\DEV\Mantra Kickstarter 2\.meteor\local\build\programs\server\boot.js:415:13)
W20171214-14:17:03.748(1)? (STDERR)     at Array.forEach (<anonymous>)
W20171214-14:17:03.748(1)? (STDERR)     at C:\DEV\Mantra Kickstarter 2\.meteor\local\build\programs\server\boot.js:414:9W20171214-14:17:03.749(1)? (STDERR)     at C:\DEV\Mantra Kickstarter 2\.meteor\local\build\programs\server\boot.js:468:5W20171214-14:17:03.749(1)? (STDERR)     at Function.run (C:\DEV\Mantra Kickstarter 2\.meteor\local\build\programs\server\profile.js:510:12)
W20171214-14:17:03.750(1)? (STDERR)     at C:\DEV\Mantra Kickstarter 2\.meteor\local\build\programs\server\boot.js:467:11
```

Meteor 1.6.1 use Babel 7 and I think something is wrong with that.
When I remove your package, my app launch...

I will report the issue on the meteor repo too.

Thanks.
Rémy.

**Comment by RemyLespagnol** [comment]
A comment from @benjamn : https://github.com/meteor/meteor/issues/9469#issuecomment-351552571

**Comment by msavin** [comment]
Thanks for reporting. I just had the chance to test on Meteor 1.7 and it works

If you run into any issues please open a new ticket.
