### ISSUE TITLE
Getting erroneous error: "There was an error updating your document. Please review your changes and try again."

### ISSUE THREAD

**Issue by GiraffeSlacks** [msavin/Mongol#39]
Any changes I make give me this error but, despite the error, my changes are saved properly. I just installed so I should be on 0.5.4.

The error at the server is:

```
I20150301-10:03:32.556(-8)? Exception while invoking method 'Mongol_update' Error: Did not check() all arguments during call to 'Mongol_update'
I20150301-10:03:32.557(-8)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150301-10:03:32.557(-8)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150301-10:03:32.557(-8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1597:1)
I20150301-10:03:32.557(-8)?     at packages/ddp/livedata_server.js:648:1
I20150301-10:03:32.557(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-10:03:32.557(-8)?     at packages/ddp/livedata_server.js:647:1
I20150301-10:03:32.558(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-10:03:32.558(-8)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150301-10:03:32.558(-8)?     at packages/ddp/livedata_server.js:546:1
```

**Comment by GiraffeSlacks** [comment]
Same for updating:

```
I20150301-10:14:19.012(-8)? Exception while invoking method 'Mongol_duplicate' Error: Did not check() all arguments during call to 'Mongol_duplicate'
I20150301-10:14:19.013(-8)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150301-10:14:19.013(-8)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150301-10:14:19.014(-8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1597:1)
I20150301-10:14:19.014(-8)?     at packages/ddp/livedata_server.js:648:1
I20150301-10:14:19.015(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-10:14:19.016(-8)?     at packages/ddp/livedata_server.js:647:1
I20150301-10:14:19.016(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150301-10:14:19.016(-8)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150301-10:14:19.017(-8)?     at packages/ddp/livedata_server.js:546:1
```

**Comment by msavin** [comment]
It looks like there's a package that's causing the issue. Could you send a list of your packages?

**Comment by GiraffeSlacks** [comment]
I'm using the Windows preview. `meteor update` has nothing to do.

```
accounts-password                1.0.6-winr.6* Password support for accounts
alanning:roles                   1.2.13  Role-based authorization
aldeed:console-me                0.1.2  Causes console.log() on the server to display on a client console as well
audit-argument-checks            1.0.3-winr.2  Try to detect inadequate input sanitization
fortawesome:fontawesome          4.2.0_2  Font Awesome (official): 470+ scalable vector icons, customizable via CSS, Retina friendly
houston:admin                    2.0.3  A zero-config Meteor Admin
ian:accounts-ui-bootstrap-3      1.2.33  Bootstrap-styled accounts-ui with multi-language support.
iron:router                      1.0.7  Routing specifically designed for Meteor
meteor-platform                  1.2.1-winr.3* Include a standard set of Meteor packages in your app
momentjs:moment                  2.9.0  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
msavin:mongol                    0.5.4  The insanely handy development package for Meteor.
sacha:spin                       2.0.4  Simple spinner package for Meteor
tsega:bootstrap3-datetimepicker  4.0.0_4  Bootstrap 3 DateTime picker from @Eonasdan, packaged for Meteor.js
twbs:bootstrap                   3.3.2  Bootstrap (official): the most popular HTML/CSS/JS framework for responsive, mobile first projects
underscore                       1.0.3-winr.2  Collection of small helpers: _.map, _.each, ...
useraccounts:bootstrap           1.5.0* Accounts Templates styled for Twitter Bootstrap.
```

**Comment by JackAdams** [comment]
Yeah, it's `audit-argument-checks` doing it. I can write a fix for this in a day or two. Just a bit busy at work right now.

**Comment by GiraffeSlacks** [comment]
Great work @msavin.
